name: Health Check

on:
  schedule:
    - cron: '30/10 * * * 0'

jobs:
  health_check:
    runs-on: ubuntu-20.04
    steps:
      - name: Check health
        uses: jtalk/url-health-check-action@v2
        with:
          url: https://hannajan-fullstack-pokedex.herokuapp.com/health